In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[6461, 7143, 3046, 9285],
 [6461, 7143, 3046, 7897],
 [6461, 3613, 3046, 7822],
 [6099, 4401, 8448, 190, 7082],
 [6099, 4401, 8448, 190, 3573],
 [2251, 6461, 2443, 3046, 750],
 [6404, 967, 3789, 190]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6461 7143 3046 9285]
 [   0    0    0    0 6461 7143 3046 7897]
 [   0    0    0    0 6461 3613 3046 7822]
 [   0    0    0 6099 4401 8448  190 7082]
 [   0    0    0 6099 4401 8448  190 3573]
 [   0    0    0 2251 6461 2443 3046  750]
 [   0    0    0    0 6404  967 3789  190]]


In [10]:
## feature representation
dim=10

In [15]:
from keras.models import Sequential
from keras.layers import Embedding

voc_size = 1000  # Replace with your vocabulary size
dim = 50  # Replace with your desired embedding dimension
sent_length = 8  # Replace with your desired sentence length

model = Sequential()
model.add(Embedding(input_dim=voc_size, output_dim=dim, input_length=sent_length))
model.compile(optimizer='adam', loss='mse')



ValueError: Unrecognized keyword arguments passed to Embedding: {'input_length': 8}

In [16]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [18]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 75ms/step


array([[[ 0.01453609,  0.03697893,  0.02267558,  0.01149287,
         -0.03695335,  0.01416664,  0.03655917,  0.00734384,
          0.03028754,  0.00339943],
        [ 0.01453609,  0.03697893,  0.02267558,  0.01149287,
         -0.03695335,  0.01416664,  0.03655917,  0.00734384,
          0.03028754,  0.00339943],
        [ 0.01453609,  0.03697893,  0.02267558,  0.01149287,
         -0.03695335,  0.01416664,  0.03655917,  0.00734384,
          0.03028754,  0.00339943],
        [ 0.01453609,  0.03697893,  0.02267558,  0.01149287,
         -0.03695335,  0.01416664,  0.03655917,  0.00734384,
          0.03028754,  0.00339943],
        [-0.03792738,  0.01958679, -0.04232483, -0.03475742,
          0.02182527,  0.01143194, -0.03125288,  0.02584182,
          0.0050171 ,  0.04725457],
        [-0.02213118,  0.00730393,  0.02797868, -0.02386508,
         -0.0024281 ,  0.04419583, -0.02011771, -0.00502002,
         -0.03373672, -0.04126013],
        [-0.02629154,  0.02487988, -0.02824695,  0.0

In [19]:
embedded_docs[0]

array([   0,    0,    0,    0, 6186, 6775,  637, 4895])

In [22]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 19ms/step


array([[ 0.01453609,  0.03697893,  0.02267558,  0.01149287, -0.03695335,
         0.01416664,  0.03655917,  0.00734384,  0.03028754,  0.00339943],
       [ 0.01453609,  0.03697893,  0.02267558,  0.01149287, -0.03695335,
         0.01416664,  0.03655917,  0.00734384,  0.03028754,  0.00339943],
       [ 0.01453609,  0.03697893,  0.02267558,  0.01149287, -0.03695335,
         0.01416664,  0.03655917,  0.00734384,  0.03028754,  0.00339943],
       [ 0.01453609,  0.03697893,  0.02267558,  0.01149287, -0.03695335,
         0.01416664,  0.03655917,  0.00734384,  0.03028754,  0.00339943],
       [-0.03792738,  0.01958679, -0.04232483, -0.03475742,  0.02182527,
         0.01143194, -0.03125288,  0.02584182,  0.0050171 ,  0.04725457],
       [-0.02213118,  0.00730393,  0.02797868, -0.02386508, -0.0024281 ,
         0.04419583, -0.02011771, -0.00502002, -0.03373672, -0.04126013],
       [-0.02629154,  0.02487988, -0.02824695,  0.0302802 , -0.01835672,
        -0.00683415,  0.01606056, -0.04426531